import { AlertTriangle, CheckCircle, MapPin, Radio } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { SeverityBadge } from './SeverityBadge';
import { formatRelativeTime } from '@/lib/utils';
import type { PublicAlert } from '@/types';

export function PublicAlertCard({ alert, detailed=false, onAcknowledge, acknowledged=false }: { alert: PublicAlert; detailed?: boolean; onAcknowledge?:()=>void; acknowledged?:boolean }) {
  return <Card className="border-red-500/30 bg-red-50"><CardContent className="p-4"><div className="flex items-start gap-3"><Radio className="mt-1 h-5 w-5 shrink-0 text-destructive" aria-hidden="true" /><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><SeverityBadge severity={alert.severity} /><span className="font-mono text-xs text-muted-foreground">{alert.alertCode}</span></div><h3 className="font-semibold">{alert.messageTitle}</h3><p className="mt-1 text-sm text-muted-foreground">{alert.messageBody}</p>{detailed && alert.safetyInstructions?.length > 0 && <div className="mt-3 rounded-md border bg-muted p-3"><p className="mb-1 text-xs font-semibold uppercase text-amber-300">Safety instructions</p><ul className="space-y-1 text-sm text-muted-foreground">{alert.safetyInstructions.map((item, i)=><li key={i} className="flex gap-2"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-300" aria-hidden="true" />{item}</li>)}</ul></div>}<div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><MapPin className="h-3 w-3" aria-hidden="true" />{alert.districtName}, {alert.stateCode}</span><span>{formatRelativeTime(alert.issuedAt)}</span></div></div>{onAcknowledge && <Button size="sm" variant={acknowledged?'outline':'default'} disabled={acknowledged} onClick={onAcknowledge}>{acknowledged?<><CheckCircle className="mr-1 h-4 w-4" aria-hidden="true" />Acknowledged</>:'Acknowledge'}</Button>}</div></CardContent></Card>;
}
